# docker-compose.yml
version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
    depends_on:
      - redis
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: slim_seed
      MYSQL_USER: slim_user
      MYSQL_PASSWORD: slim_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

volumes:
  mysql_data: