version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: slimseed_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=slim_seed
      - DB_USER=slim_user
      - DB_PASS=slim_pass

  mysql:
    image: mysql:8.0
    container_name: slimseed_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: slim_seed
      MYSQL_USER: slim_user
      MYSQL_PASSWORD: slim_pass
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: slimseed_redis
    ports:
      - "6380:6379"

volumes:
  mysql_data: