version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: {{PROJECT_NAME}}_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./data:/var/www/html/data
    depends_on:
      - redis
    environment:
      - DB_DRIVER=sqlite
      - DB_NAME=data/{{DB_NAME}}

  redis:
    image: redis:7-alpine
    container_name: {{PROJECT_NAME}}_redis
    ports:
      - "6380:6379"
