version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: {{PROJECT_NAME}}_app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME={{DB_NAME}}
      - DB_USER={{DB_USER}}
      - DB_PASS={{DB_PASS}}

  postgres:
    image: postgres:15-alpine
    container_name: {{PROJECT_NAME}}_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: {{DB_NAME}}
      POSTGRES_USER: {{DB_USER}}
      POSTGRES_PASSWORD: {{DB_PASS}}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: {{PROJECT_NAME}}_redis
    ports:
      - "6380:6379"

volumes:
  postgres_data:
